import {products,formats,money,getLang,t,bulkUnitPrice} from './catalog.js';
import {initCommerce,openProduct,addToCart,openCart,openSearch} from './commerce.js';
let selectedFormat='sachet';
let toastTimer;
const $=s=>document.querySelector(s);
const esc=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const num=v=>new Intl.NumberFormat(getLang()==='ar'?'ar-SA':'en-SA').format(v);
function toast(text){$('#toast').textContent=text;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3400);}
function renderProducts(){const f=formats.find(f=>f.id===selectedFormat);$('#product-grid').innerHTML=products.slice(0,4).map(p=>`<article class="product-card" style="--flavour:${p.color};--tint:${p.pale}"><button class="product-image-button" data-product="${p.id}" aria-label="${esc(t('تفاصيل '+p.name.ar,p.name.en+' details'))}"><span class="product-note">${esc(p.note[getLang()])}</span><img src="${p.image}" alt="${esc(p.name[getLang()]+t(' — تصميم الكيس الفردي',' — single sachet artwork'))}" width="1086" height="1448" loading="lazy"><span class="product-open" aria-hidden="true">↗</span></button><h3><button data-product="${p.id}">${esc(p.name[getLang()])}</button></h3><div class="product-meta"><span>${esc(f.name[getLang()])} · ${num(f.count)} × ${num(30)} ${t('غ','g')}</span><span>${num(f.grams)} ${t('غ إجمالي','g total')}</span></div><button class="product-add" data-add="${p.id}" aria-label="${esc(t('أضف '+p.name.ar+' إلى السلة','Add '+p.name.en+' to bag'))}"><span>${money(f.price)}</span><span>${t('أضف للسلة','Add to bag')} +</span></button></article>`).join('');
$('#format-explanation').textContent=selectedFormat==='sachet'?t('كيس مغلق، نكهة واحدة، ٣٠ غ. صور العبوات تصاميم تصوّرية.','One sealed sachet, one flavour, 30 g. Packaging images are design concepts.'):selectedFormat==='cup'?t('كوب الرحلة: ٥ أكياس مغلقة من نكهة واحدة + كيس منفصل للقشور. الصورة تعرض تصميم الكيس؛ شاهد محتويات الكوب في التفاصيل.','Journey Cup: five sealed same-flavour sachets + a separate shell bag. Sachet artwork shown; see cup contents in product details.'):t('كرتون التجزئة: ٢٤ كيسًا من نكهة واحدة. الصور تعرض تصميم الكيس الفردي.','Retail case: 24 sachets of one flavour. Images show individual sachet artwork.');
$('#family-price').textContent=money(39);
}
function updateBulk(){const input=$('#bulk-quantity');const q=Number(input.value);const valid=Number.isInteger(q)&&q>=4&&q<=10000;if(!valid){$('#bulk-total').textContent='—';$('#bulk-count').textContent=t('أدخل عددًا صحيحًا من ٤ إلى ١٠٬٠٠٠.','Enter a whole number from 4 to 10,000.');return;}
$('#bulk-total').textContent=money(q*bulkUnitPrice(q));$('#bulk-count').textContent=`${num(q*24)} ${t('كيس','sachets')} · ${num(q*.72)} ${t('كغ إجمالي','kg total')}`;
let nudge=$('#bulk-nudge');if(!nudge){nudge=document.createElement('div');nudge.id='bulk-nudge';nudge.className='bulk-nudge';$('#bulk-count').after(nudge);}nudge.textContent=q===23?t('أضف كرتونًا واحدًا ووفّر ١٠ ر.س في إجمالي المنتجات المقترح.','Add one case and save SAR 10 on the proposed goods subtotal.'):'';
document.querySelectorAll('.bulk-table tbody tr').forEach((r,i)=>r.dataset.active=String(i===(q>=24?2:q>=12?1:0)));
}
function renderBulkOptions(){const value=$('#bulk-flavour').value;$('#bulk-flavour').innerHTML=products.slice(0,4).map(p=>`<option value="${p.id}">${p.name[getLang()]}</option>`).join('');if(products.some(p=>p.id===value))$('#bulk-flavour').value=value;updateBulk();}
function applyLanguage(lang){document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.querySelectorAll('[data-ar][data-en]').forEach(e=>e.textContent=e.dataset[lang]);document.querySelectorAll('[data-alt-ar]').forEach(e=>e.alt=e.dataset[lang==='ar'?'altAr':'altEn']);$('#language-toggle').textContent=lang==='ar'?'EN':'عربي';$('#language-toggle').setAttribute('aria-label',lang==='ar'?'Switch to English':'التبديل إلى العربية');document.title=lang==='ar'?'حُبّ | للّمة طعم — HUBB السعودية':'HUBB | A little HUBB. A lot of together.';try{localStorage.setItem('hubb-language',lang);}catch{}renderProducts();renderBulkOptions();window.dispatchEvent(new Event('hubb:language'));}
const dialog=$('#editorial-dialog');const content=$('#editorial-content');let dialogOpener;
function showDialog(html){dialogOpener=document.activeElement;content.innerHTML=html;if(!dialog.open)dialog.showModal();}
function closeDialog(){dialog.close();content.innerHTML='';dialogOpener?.focus?.();}
$('.dialog-close').addEventListener('click',closeDialog);dialog.addEventListener('click',e=>{if(e.target===dialog){const r=dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)closeDialog();}});dialog.addEventListener('close',()=>{content.innerHTML='';});
function showMoment(id){const m={majlis:{title:t('سوالف ما تخلص','One more story'),body:t('قهوة على الطاولة، كيس ينفتح، وسالفة تجرّ سالفة. تصوّر لحملة حُبّ في المجلس السعودي.','Coffee on the table. A pack opens. One story becomes another. A HUBB campaign concept set in a Saudi majlis.'),product:'sea-salt'},roadtrip:{title:t('الطريق له رفيق','Take the long way'),body:t('وقفة هادئة على الطريق. افتح كوب الرحلة، خذ كيسًا وخلّ الباقي مغلقًا. مشهد تصوّري في استراحة آمنة والسيارة متوقفة.','A quiet stop along the way. Open a Journey Cup, take one sachet and keep the others sealed. A concept scene at a safe stop with the car parked.'),product:'pepper-lime'},game:{title:t('باقي جولة','Just one more round'),body:t('كل واحد له نكهته، وباقي جولة تجمعنا. تصوّر لحملة حُبّ حول جلسة لعب ومشاركة.','Everyone has a flavour. There’s still one more round. A HUBB campaign concept around a shared game-night table.'),product:'family-mix'}}[id];showDialog(`<p class="eyebrow">${t('مشهد حملة مولّد بالذكاء الاصطناعي','AI-GENERATED CAMPAIGN CONCEPT')}</p><h2>${m.title}</h2><img src="./assets/ugc-${id}.webp" alt="${esc(m.title)}"><p style="margin-top:20px">${m.body}</p><button class="button primary" id="moment-shop">${t('تسوّق هذه اللحظة','Shop this moment')} <span class="direction-arrow">←</span></button>`);$('#moment-shop').onclick=()=>{closeDialog();openProduct(m.product,m.product==='family-mix'?'family':'cup');};}
const info={delivery:()=>`<h2>${t('التوصيل والاسترجاع','Delivery & returns')}</h2><p>${t('المتجر في مرحلة المعاينة. مناطق التوصيل، الرسوم، مواعيد التسليم وسياسة الاسترجاع لم تُعتمد بعد. لا يتم إرسال أي طلب أو تحصيل أي مبلغ من هذه النسخة.','The store is in preview. Delivery areas, charges, delivery times and return policies are not yet approved. This version does not send orders or collect payments.')}</p><p>${t('ستظهر التفاصيل المعتمدة قبل فتح البيع، مع طريقة واضحة للتواصل مع خدمة العملاء. لطلبات الأعمال، استخدم حاسبة الجملة لتنزيل طلب عرض سعر مبدئي.','Approved details and a clear customer-support contact will appear before sales open. For business orders, use the wholesale calculator to download a draft quote request.')}</p>`,privacy:()=>`<h2>${t('الخصوصية والشروط','Privacy & terms')}</h2><p>${t('هذه نسخة تجريبية. تُحفظ محتويات السلة واختيار اللغة على هذا المتصفح فقط. لا تُرسل النماذج إلى خادم ولا تُحفظ بيانات الاسم أو العنوان أو الهاتف. تُمسح بيانات النماذج عند إغلاقها.','This is a preview. Cart contents and language preference are stored only in this browser. Forms are not sent to a server, and names, addresses or telephone numbers are not saved. Form details are cleared when the form closes.')}</p><p>${t('طلب عرض السعر ملف ينزّل على جهازك باختيارك. ملاحظات التقييم تظهر في المعاينة الحالية فقط. الخطوط تُحمّل من Google Fonts؛ لا توجد أدوات إعلانات أو تحليلات في هذه النسخة.','A quote request is downloaded to your device only when you choose. Review feedback appears only in the current preview. Fonts are loaded from Google Fonts; this version has no advertising or analytics tools.')}</p><p>${t('الشروط التجارية وسياسة الخصوصية النهائية تحتاج اعتماد المنشأة قبل استقبال طلبات فعلية.','Final commercial terms and privacy policy require business approval before live orders are accepted.')}</p><button class="button secondary" id="clear-preferences">${t('مسح اللغة المحفوظة','Clear saved language')}</button>`,creators:()=>`<p class="eyebrow">HUBB / CREATOR CORNER</p><h2>${t('حكايتك، بطريقتك.','Your story. Your way.')}</h2><p>${t('نطوّر مساحة لحكايات حُبّ من صنّاع المحتوى في السعودية. أفكار البداية: جلسة مجلس، استراحة رحلة والسيارة متوقفة، أو ليلة لعب.','We’re developing a space for HUBB stories by Saudi creators. Starting ideas: a majlis gathering, a road-trip break with the car parked, or a game night.')}</p><h3>${t('تفاصيل تحكي المنتج','Let the product tell the story')}</h3><p>${t('أظهر الكيس المغلق، النكهة وطريقة المشاركة. إذا ظهر الأكل، افتح القشر وافصله، كُل النواة فقط واجمع القشور في الكيس المخصص.','Show the sealed sachet, the flavour and the way it is shared. If eating is shown, crack and separate the husk, eat only the kernel and collect husks in the separate shell bag.')}</p><p class="small-text">${t('التقديم للحملة لم يُفتح بعد. الصور الحالية مشاهد مولّدة، وليست شهادات صنّاع محتوى.','Campaign applications are not open yet. Current images are generated scenes, not creator endorsements.')}</p>`};
function showInfo(id){showDialog(info[id]());$('#clear-preferences')?.addEventListener('click',()=>{try{localStorage.removeItem('hubb-language');}catch{}toast(t('تم مسح اللغة المحفوظة.','Saved language preference cleared.'));});}
function showReview(){showDialog(`<p class="eyebrow">${t('ملاحظات على التجربة · غير منشورة','CONCEPT FEEDBACK · NOT PUBLISHED')}</p><h2>${t('وش رأيك؟','What do you think?')}</h2><p>${t('جرّب نموذج التقييم. لن تُنشر ملاحظتك أو تُضاف كتقييم شراء موثّق.','Try the review form. Your feedback won’t be published or added as a verified purchase review.')}</p><form id="review-form"><label for="review-product">${t('المنتج','Product')}</label><select id="review-product">${products.map(p=>`<option>${p.name[getLang()]}</option>`).join('')}</select><label>${t('تقييم تجربة التصميم','Rate the design experience')}</label><div class="rating-picker" role="group" aria-label="${t('تقييم من ١ إلى ٥','Rating from 1 to 5')}">${[1,2,3,4,5].map(n=>`<label><input type="radio" name="rating" value="${n}" required>${n} ☆</label>`).join('')}</div><label for="review-text">${t('ملاحظتك','Your feedback')}</label><textarea id="review-text" required minlength="10" maxlength="1500" placeholder="${t('اكتب ١٠ أحرف على الأقل','At least 10 characters')}"></textarea><button type="submit" class="button primary">${t('عاين ملاحظتك','Preview your feedback')}</button></form>`);$('#review-form').onsubmit=e=>{e.preventDefault();const rating=new FormData(e.target).get('rating');const message=$('#review-text').value;const product=$('#review-product').value;content.innerHTML=`<p class="eyebrow">${t('معاينة فقط · لم تُرسل','PREVIEW ONLY · NOT SENT')}</p><h2>${t('وصلت للمعاينة.','Your feedback preview.')}</h2><div class="inline-success"><strong>${esc(product)} · ${esc(rating)}/5</strong><p style="margin-top:13px;white-space:pre-wrap">${esc(message)}</p></div><p style="margin-top:20px">${t('تظهر ملاحظتك هنا مؤقتًا. لم يتم حفظها أو نشرها أو إضافتها للتقييمات.','Your feedback appears here temporarily. It has not been saved, published or added to the reviews.')}</p>`;};}
function showBulkRequest(){const q=Number($('#bulk-quantity').value);if(!Number.isInteger(q)||q<4||q>10000)return;const p=products.find(p=>p.id===$('#bulk-flavour').value);showDialog(`<p class="eyebrow">${t('طلب عرض سعر · مسودة','QUOTE REQUEST · DRAFT')}</p><h2>${t('حُبّ لأعمالك.','HUBB for your business.')}</h2><p>${esc(p.name[getLang()])} · ${num(q)} ${t('كرتون','cases')} · ${num(q*24)} ${t('كيس','sachets')}<br>${t('إجمالي المنتجات المقترح:','Proposed goods subtotal:')} ${money(q*bulkUnitPrice(q))}</p><form id="quote-form"><label for="quote-company">${t('اسم المنشأة','Business name')}</label><input id="quote-company" name="company" required maxlength="100" autocomplete="organization"><label for="quote-city">${t('المدينة','City')}</label><input id="quote-city" name="city" required maxlength="80" autocomplete="address-level2"><label for="quote-notes">${t('ملاحظات التوريد (اختياري)','Supply notes (optional)')}</label><textarea id="quote-notes" name="notes" maxlength="1200"></textarea><p class="small-text" style="margin-top:15px">${t('تنزيل مسودة على جهازك فقط. لا تُرسل البيانات ولا تُحفظ في المتصفح. الشحن والضرائب وشروط التوريد تُضاف في عرض السعر النهائي.','Downloads a draft to your device only. Details are not sent or saved in the browser. Freight, tax and supply terms belong in the final quotation.')}</p><button type="submit" class="button primary">${t('تنزيل طلب عرض السعر','Download quote request')} ↓</button></form>`);$('#quote-form').onsubmit=e=>{e.preventDefault();const d=new FormData(e.target);const body=`HUBB — ${t('مسودة طلب عرض سعر','Draft quote request')}\n${t('لم يُرسل — ليس طلب شراء مؤكدًا','NOT SENT — NOT A CONFIRMED PURCHASE ORDER')}\n\n${t('المنشأة','Business')}: ${d.get('company')}\n${t('المدينة','City')}: ${d.get('city')}\n${t('المنتج','Product')}: ${p.name.en} / ${p.name.ar}\n${t('الكمية','Quantity')}: ${q} cases × 24 sachets × 30 g\n${t('الإجمالي','Total')}: ${q*24} sachets / ${(q*.72).toFixed(2)} kg\n${t('سعر الكرتون المقترح','Proposed case price')}: SAR ${bulkUnitPrice(q).toFixed(2)}\n${t('إجمالي المنتجات المقترح','Proposed goods subtotal')}: SAR ${(q*bulkUnitPrice(q)).toFixed(2)}\n\n${t('ملاحظات','Notes')}: ${d.get('notes')||'—'}\n\n${t('الأسعار مقترحة وتحتاج تأكيد المصنع. الضرائب والشحن والمخزون وشروط الدفع والتوريد غير مشمولة أو مؤكدة. لا تُحصّل مبالغ ولا يُرسل هذا الطلب تلقائيًا.','Prices are proposed and require factory confirmation. Tax, shipping, stock, payment and supply terms are not included or confirmed. No payment is collected and this draft is not sent automatically.')}\n`;
const blob=new Blob(['\ufeff'+body],{type:'text/plain;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`HUBB-quote-request-${q}-cases.txt`;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);content.innerHTML=`<p class="eyebrow">${t('مسودة محلية · لم تُرسل','LOCAL DRAFT · NOT SENT')}</p><h2>${t('طلبك جاهز للمراجعة.','Ready for a conversation.')}</h2><p>${t('تم تجهيز تنزيل ملف طلب عرض السعر. راجعه وشاركه مع فريق المبيعات عندما يتم تحديد وسيلة التواصل. لم يُرسل طلب شراء أو تُحفظ بياناتك.','Your draft quote-request download is prepared. Review it and share it with sales once the contact route is confirmed. No purchase order was sent and your details were not saved.')}</p><pre class="draft-output">${esc(body)}</pre>`;};}
initCommerce();
let preferred='ar';try{preferred=localStorage.getItem('hubb-language')==='en'?'en':'ar';}catch{}applyLanguage(preferred);
$('#language-toggle').onclick=()=>{if(dialog.open)closeDialog();applyLanguage(getLang()==='ar'?'en':'ar');};$('#search-button').onclick=openSearch;$('#cart-button').onclick=openCart;$('#review-button').onclick=showReview;
document.addEventListener('click',e=>{const product=e.target.closest('[data-product]');if(product)openProduct(product.dataset.product,product.dataset.productFormat||selectedFormat);const add=e.target.closest('[data-add]');if(add){addToCart(add.dataset.add,selectedFormat,1);toast(t('انضاف للسلة. جاهز للّمة.','Added to your bag. A little more HUBB.'));}const infoButton=e.target.closest('[data-info]');if(infoButton)showInfo(infoButton.dataset.info);const moment=e.target.closest('[data-moment]');if(moment)showMoment(moment.dataset.moment);const change=e.target.closest('[data-bulk-change]');if(change){const current=Number($('#bulk-quantity').value)||4;$('#bulk-quantity').value=Math.min(10000,Math.max(4,current+Number(change.dataset.bulkChange)));updateBulk();}});
document.querySelectorAll('[data-format]').forEach(button=>button.onclick=()=>{selectedFormat=button.dataset.format;document.querySelectorAll('[data-format]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));renderProducts();});
$('#bulk-quantity').addEventListener('input',updateBulk);$('#bulk-form').onsubmit=e=>{e.preventDefault();if(e.target.reportValidity())showBulkRequest();};$('#mobile-toggle').onclick=()=>{const open=$('#mobile-nav').hidden;$('#mobile-nav').hidden=!open;$('#mobile-toggle').setAttribute('aria-expanded',String(open));};$('#mobile-nav').addEventListener('click',e=>{if(e.target.closest('a')){$('#mobile-nav').hidden=true;$('#mobile-toggle').setAttribute('aria-expanded','false');}});
