const esc=s=>s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('"','&quot;');
export function renderCare(lang='ar'){
 const t=(ar,en)=>lang==='ar'?ar:en;
 const image=(src,alt,cls='')=>`<img class="${cls}" src="/assets/${src}.webp" width="1024" height="1536" loading="lazy" alt="${esc(alt)}">`;
 return `<section id="story" class="care-section wrap section">
 <div class="care-heading"><p class="eyebrow">${t('بحُبّ، من حريملاء','WITH LOVE, FROM HURAYMILA')}</p><h2>${t('منّا <em class="ink-word">الاهتمام.</em><br>ومنكم <em class="ink-word">اللمّة.</em>','From us, <em class="ink-word">the care.</em><br>From you, <em class="ink-word">the gathering.</em>')}</h2></div>
 <div class="care-cards">
 <article class="care-card care-detail" data-care-card><div class="care-art" aria-hidden="true"><span class="care-numeral">02</span>${image('ritual-whole-edge-v5','','care-seed')}${image('ritual-kernel-v4','','care-kernel')}</div><div class="care-caption"><h3>${t('سنتين من <em class="ink-word">الاهتمام.</em>','Two years of <em class="ink-word">care.</em>')}</h3><p>${t('للطقّة. للقرمشة. للنكهة.','For the crack. The crunch. The flavour.')}</p></div></article>
 <article class="care-card care-flavours" data-care-card><div class="care-art care-fan" aria-hidden="true">${['sea-salt','garlic-salt','pepper-lime','fire-salt'].map((id,i)=>`<img src="/assets/${id}.webp" alt="" width="1024" height="1536" loading="lazy" style="--fan-i:${i-1.5}">`).join('')}</div><div class="care-caption"><h3>${t('كل واحد له <em class="ink-word">حُبّه.</em>','Find your little <em class="ink-word">HUBB.</em>')}</h3><p>${t('أربع نكهات. وكلنا في اللمّة.','Four flavours. Everyone belongs.')}</p></div></article>
 <article class="care-card care-together" data-care-card><div class="care-art"><img src="/assets/ugc-table-v3.webp" width="1024" height="1536" loading="lazy" alt="${t('تصوّر لعائلة تتشارك حُبّ بعد الأكل','Family sharing HUBB after a meal, generated concept')}"></div><div class="care-caption"><h3>${t('والحين… <em class="ink-word">مرّر حُبّ.</em>','Now, <em class="ink-word">pass it around.</em>')}</h3><p>${t('خلّ السوالف تطول.','Let the conversation stay a little longer.')}</p><small>${t('مشهد تصوّري · مولّد بالذكاء الاصطناعي','CREATIVE CONCEPT · AI GENERATED')}</small></div></article>
 </div>
 <details class="care-details"><summary>${t('حكايتنا، لمن يحب يعرف أكثر','Our story, if you’d like a little more')} <span aria-hidden="true">+</span></summary><p>${t('نطوّر حُبّ ونصنعه في مصنعنا بحريملاء، في السعودية. قضينا سنتين نشتغل على حجم الحبّة، وإحساس الكسر، وقرمشة النواة والنكهة اللي توصل لها. رجعنا للتحميص والتجربة مرّة بعد مرّة. اليوم نبدأ بأربع نكهات، وملاحظاتكم تساعدنا نطوّر اللي جاي. ونطمح نوسّع التجربة في عالم المكسرات والبذور.','We develop and make HUBB at our factory in Huraymila, Saudi Arabia. We spent two years working on seed size, the feel of the crack, kernel crunch and flavour inside—returning to the roast and trying again. Today, we begin with four flavours. Your tasting notes help shape what comes next. Our ambition also reaches into other nuts and seeds.')}</p></details>
 </section>
 <section id="reviews" class="care-review"><div class="wrap care-review-inner"><div><p class="eyebrow">${t('جرّبت حُبّ؟','TRIED HUBB?')}</p><h2>${t('الحين، <em class="ink-word">دورك.</em>','Now, <em class="ink-word">your turn.</em>')}</h2><p>${t('وش عجبك؟ وش نقدر نحسّنه؟','What did you love? What could be better?')}</p></div><div class="care-review-action"><div class="care-review-words" aria-hidden="true"><span>${t('الطقّة','The crack.')}</span><span>${t('القرمشة','The crunch.')}</span><span>${t('النكهة','The flavour.')}</span></div><button class="button primary" id="review-button">${t('شاركنا رأيك','Share your thoughts')} <span aria-hidden="true">↗</span></button><small>${t('ما نُشرت تقييمات شراء موثّقة حتى الآن.','No verified purchase reviews published yet.')}</small></div></div></section>
 <section id="partners" class="care-partners wrap section"><div class="section-heading"><div><p class="eyebrow">${t('نصنعها هنا. ونكبر معكم.','MADE HERE. GROWN TOGETHER.')}</p><h2>${t('خلّ لحُبّ <em class="ink-word">مكان.</em>','Make room for <em class="ink-word">HUBB.</em>')}</h2></div></div><div class="care-partner-grid">
 <article class="care-partner-card"><div class="partner-art">${image('case-sea-salt-display-v4',t('تصميم كرتون عرض حُبّ، ٢٤ كيسًا','HUBB 24-sachet display carton concept'))}</div><div><h3>${t('على رفّك.','On your shelf.')}</h3><p>${t('تجزئة · توزيع · ضيافة','Retail · Distribution · Hospitality')}</p><a href="#wholesale" class="text-link">${t('استفسار جملة','Wholesale enquiry')} ↗</a><button data-partner="distribution" class="text-link">${t('ناقش فرصة التوزيع','Discuss distribution')} ↗</button></div></article>
 <article class="care-partner-card"><div class="partner-art partner-photo"><img src="/assets/ugc-majlis.webp" width="1024" height="1536" loading="lazy" alt="${t('تصوّر لحُبّ في جلسة مجلس','Imagined HUBB majlis moment, generated concept')}"><small>${t('مشهد تصوّري · مولّد بالذكاء الاصطناعي','AI-GENERATED CONCEPT')}</small></div><div><h3>${t('في حكايتك.','In your story.')}</h3><p>${t('ذوق حُبّ. واحكِها بطريقتك.','Taste HUBB. Tell it your way.')}</p><button data-partner="collaboration" class="text-link">${t('اقترح تعاون','Propose a collaboration')} ↗</button></div></article>
 </div></section>`;
}
