import {sitePath} from './paths.js';
const pair=(ar,en)=>({ar,en});
export const scenes=[
{id:'road',product:'sea-salt',color:'#31576b',image:'/assets/story-road-v4.webp',frame:1,place:pair('ملح بحري · للمشوار','CLASSIC SEA SALT · THE JOURNEY'),title:pair('للمشوار رفيق.','Good company for the road.'),body:pair('من الرياض للدمام. وقفة، كيس حُبّ، وباقي المشوار مع ناسك.','Riyadh to Dammam. A pause, a little HUBB, and good company along the way.'),cta:pair('اكتشف الملح البحري','Explore Classic Sea Salt'),beats:[pair('جهّز المشوار','Pack for the road'),pair('خذ لك وقفة','Take a little pause'),pair('استمتع بحبّة','Enjoy the moment'),pair('وصلنا للّمة','Arrive together')]},
{id:'gaming',product:'fire-salt',color:'#a33f2b',image:'/assets/story-gaming-v4.webp',frame:2,place:pair('ملح حار · ليلة اللعب','FIRE SALT · GAME NIGHT'),title:pair('باقي جولة.','One more round.'),body:pair('اليد ترتاح من اللعب. كيس ينفتح. وبعدها… دورك.','Controller down. A pack opens. A smile across the sofa. Your turn.'),cta:pair('اكتشف الملح الحار','Explore Fire Salt'),beats:[pair('قربت تفوز','Almost there'),pair('استراحة صغيرة','Take a break'),pair('غيّر جوّك','A little heat'),pair('الحين دورك','Your turn')]},
{id:'family',product:'pepper-lime',color:'#4e6737',image:'/assets/story-family-v4.webp',frame:2,place:pair('فلفل ولايم · زيارة الأهل','PEPPER LIME · FAMILY TIME'),title:pair('خلك معنا شوي.','Stay a little longer.'),body:pair('مكان جنبك، وسالفة نحب نسمعها مرة ثانية.','A place beside you. A familiar story. A few more minutes together.'),cta:pair('اكتشف فلفل ولايم','Explore Pepper Lime'),beats:[pair('وسّعوا الجلسة','Make a little room'),pair('خذ لك كيس','Pick your pack'),pair('كمّل السالفة','Tell it again'),pair('خلّنا نطوّلها','Stay a little longer')]},
{id:'tv',product:'garlic-salt',color:'#9b7229',image:'/assets/story-tv-v4.webp',frame:2,place:pair('ملح بالثوم · جلسة التلفزيون','GARLIC SALT · A NIGHT IN'),title:pair('الجلسة تحلى معكم.','The best seat is together.'),body:pair('اختاروا شيء تتابعونه. قرّبوا حُبّ. وخذوا راحتكم.','Something good on TV. HUBB within reach. Nowhere else to be.'),cta:pair('اكتشف ملح الثوم','Explore Garlic Salt'),beats:[pair('خذ راحتك','Settle in'),pair('افتح حُبّ','Open a little HUBB'),pair('شفت هاللقطة؟','Did you see that?'),pair('جلسة على راحتنا','Stay right here')]}
];
export const familyScene={id:'sharing',image:'/assets/story-sharing-v4.webp',frame:2,beats:[pair('اجتمعنا','Together again'),pair('فيه مكان','Room on the bench'),pair('كل واحد ونكهته','Pick your favourite'),pair('نكمل سوا','Back together')]};
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function framePhoto(scene,frame,alt,{eager=false}={}){return `<div class="frame-photo" style="--col:${frame%2};--row:${Math.floor(frame/2)}"><img src="${sitePath(scene.image)}" width="1254" height="1254" alt="${esc(alt)}" ${eager?'fetchpriority="high"':'loading="lazy"'} decoding="async"></div>`;}

export function photoSequence(scene,lang='ar'){
 const attrs=scene.beats.map((b,i)=>`data-beat${i}-ar="${esc(b.ar)}" data-beat${i}-en="${esc(b.en)}"`).join(' ');
 return `<div class="photo-sequence" data-photo-sequence="${scene.id}" ${attrs}>${scene.beats.map((b,i)=>`<div class="photo-sequence-layer" data-photo-frame="${i}">${framePhoto(scene,i,b[lang])}<span class="photo-frame-label">${esc(b[lang])}</span></div>`).join('')}<div class="sequence-caption" aria-hidden="true">${esc(scene.beats[0][lang])}</div><div class="sequence-meter" aria-hidden="true"><i></i></div></div>`;
}

for(const s of scenes){s.format="cup";s.alt=s.place;s.detail=pair("كوب الرحلة · خمسة أكياس مغلقة","JOURNEY CUP · FIVE SEALED SACHETS");}
export function renderScenes(lang='ar'){
const tr=(ar,en)=>lang==='ar'?ar:en;
const at=(s,key)=>esc(s[key][lang]);
return `<section id="moments" class="scene-story"><div class="scene-intro wrap"><div><p class="eyebrow">${tr('حُبّ يعيش مع يومك','HUBB, WHERE LIFE HAPPENS')}</p><h2>${tr('كل لمّة، لها حُبّ.','Different days.<br>The same little HUBB.')}</h2></div><div class="scene-intro-aside"><p>${tr('من وقفة على الطريق، إلى ليلة لعب وسوالف الأهل. شف حُبّ في لحظات مختلفة.','From a road-stop conversation to game night and family time. Find your little HUBB moment.')}</p><span class="scene-scroll-cue">${tr('كمّل نزول، تتغيّر اللحظة','KEEP SCROLLING. FIND YOUR MOMENT.')} ↓</span></div></div>
<nav class="scene-nav wrap" aria-label="${tr('اختر لحظتك','Choose your moment')}">${scenes.map((s,i)=>`<a href="#moment-${s.id}" data-scene-link="${s.id}" ${i===0?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${at(s,'place')}</a>`).join('')}</nav>
<div class="scene-body wrap"><div class="scene-stage"><div class="scene-stage-inner">${scenes.map((s,i)=>`<div class="scene-stage-image ${i===0?'is-active':''}" data-scene-image="${s.id}" ${i!==0?'aria-hidden="true"':''}>${photoSequence(s,lang)}</div>`).join('')}<div class="scene-stage-top"><span>HUBB / ${tr('لحظات نتخيّلها','MOMENTS WE IMAGINE')}</span><span class="scene-stage-number" aria-hidden="true">01 / 04</span></div><div class="scene-stage-bottom"><span class="scene-location">${at(scenes[0],'place')}</span><span class="scene-concept">${tr('تصوّر إبداعي مولّد بالذكاء الاصطناعي','AI-GENERATED CREATIVE CONCEPT')}</span></div><div class="scene-stage-progress" aria-hidden="true"><i></i></div></div></div>
<div class="scene-chapters">${scenes.map((s,i)=>`<article class="scene-chapter ${i===0?'is-active':''}" id="moment-${s.id}" data-scene="${s.id}"><div class="scene-chapter-inner"><figure class="scene-mobile-image">${photoSequence(s,lang)}<figcaption>${tr('مشهد تصوّري · مولّد بالذكاء الاصطناعي','CREATIVE CONCEPT · AI GENERATED')}</figcaption></figure><div class="scene-chapter-copy"><p class="scene-kicker"><span>${String(i+1).padStart(2,'0')}</span> / ${at(s,'place')}</p><h3>${at(s,'title')}</h3><p class="scene-description">${at(s,'body')}</p><span class="scene-pack-detail">${at(s,'detail')}</span><button class="scene-shop" data-product="${s.product}" data-product-format="${s.format}">${at(s,'cta')} <span aria-hidden="true">↗</span></button></div></div></article>`).join('')}</div></div>
<div class="scene-outro wrap"><p>${tr('قصص نتخيّلها لحُبّ. وننتظر قصتك أنت.','These are moments we imagine for HUBB. We’d love to hear yours.')}</p><button class="text-link" data-partner="collaboration">${tr('شاركنا فكرتك','Bring us your idea')} ↗</button></div></section>`;
}
