export const scenes=[
{id:'football',image:'/assets/ugc-football-v3.webp',place:{ar:'على طرف الملعب',en:'AT THE PITCH'},title:{ar:'أحلى تمريرة، بين الشوطين.',en:'A good pass. A better half-time.'},body:{ar:'استراحة قصيرة. أحد يمرّر عبوة العائلة، وكل واحد يختار نكهته. سوالف الفريق تكمل، وبعدها نرجع للملعب.',en:'A pause on the sidelines. A family pack passes down the bench. Everyone picks a flavour, the conversation carries on, and then it’s back to the game.'},detail:{ar:'للجلسة بين الشوطين · ٢٠ كيسًا مغلقًا',en:'FOR THE BREAK BETWEEN HALVES · 20 SEALED SACHETS'},cta:{ar:'حُبّ للفريق',en:'Bring HUBB for the team'},product:'family-mix',format:'family',alt:{ar:'تصوّر لأصدقاء بالغين في استراحة كرة قدم يتشاركون عبوة حُبّ',en:'Concept of adult football friends sharing HUBB during a sideline break'}},
{id:'workbreak',image:'/assets/ugc-workbreak-v3.webp',place:{ar:'فسحة من يوم العمل',en:'A LITTLE BREAK AT WORK'},title:{ar:'خمس دقايق. ولمّة حلوة.',en:'Five minutes. Good company.'},body:{ar:'بعد الغداء، وقبل ما نكمّل اليوم. كوب ينفتح، كيس ينتقل لزميل، وسالفة بسيطة تقرّبنا أكثر.',en:'Lunch is finished. There’s a little time before everyone heads back. A cup opens, a sachet goes to a colleague, and a little conversation brings everyone closer.'},detail:{ar:'كوب واحد · خمسة أكياس من النكهة نفسها',en:'ONE CUP · FIVE SAME-FLAVOUR SACHETS'},cta:{ar:'خذ حُبّ معك',en:'Pack a little HUBB'},product:'pepper-lime',format:'cup',alt:{ar:'تصوّر لزملاء بالغين يتشاركون حُبّ في استراحة العمل',en:'Concept of adult colleagues sharing HUBB in a Saudi work break room'}},
{id:'table',image:'/assets/ugc-table-v3.webp',place:{ar:'بعد الأكل، تبدأ السوالف',en:'AFTER THE FOOD, ONE MORE STORY'},title:{ar:'اللمّة تستاهل نطوّلها.',en:'Stay for one more story.'},body:{ar:'خلص الغداء، وأحد يبدأ سالفة نعرفها. ونقعد نسمعها من جديد. أربع نكهات في وسط اللمّة، وحُبّ يجمع الأجيال.',en:'The meal is over. Someone starts a story you’ve heard before, and you stay to hear it again. Four flavours in the middle. A little HUBB for every generation.'},detail:{ar:'أربع نكهات · خمسة أكياس من كل نكهة',en:'FOUR FLAVOURS · FIVE SACHETS OF EACH'},cta:{ar:'خلطة لكل اللمّة',en:'A mix for the whole table'},product:'family-mix',format:'family',alt:{ar:'تصوّر لأفراد عائلة بالغين من أجيال مختلفة يتشاركون حُبّ بعد الغداء',en:'Concept of an adult family across generations sharing HUBB after a meal'}},
{id:'parked',image:'/assets/ugc-parked-v3.webp',place:{ar:'استراحة على الطريق',en:'PULL IN. TAKE A MOMENT.'},title:{ar:'حتى الوقفة لها حكاية.',en:'A stop becomes a story.'},body:{ar:'السيارة واقفة، والرحلة لها بقية. خذ وقتك في الاستراحة: افتح كيسًا، واستمتع باللحظة، وخلّ البقية مغلقة لبعدين.',en:'The car is parked. There’s more road ahead. Take your time at the stop: open one sachet, enjoy the pause, and keep the rest sealed for later.'},detail:{ar:'وقت الاستراحة، والسيارة متوقفة',en:'A REST-STOP MOMENT WITH THE CAR PARKED'},cta:{ar:'كوب للرحلة',en:'Find your Journey Cup'},product:'sea-salt',format:'cup',alt:{ar:'تصوّر لاستراحة حُبّ بجانب سيارة متوقفة في رحلة سعودية',en:'Concept of a HUBB break with a parked car at a Saudi road rest stop'}}
];
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function renderScenes(lang='ar'){
const tr=(ar,en)=>lang==='ar'?ar:en;
const at=(s,key)=>escape(s[key][lang]);
return `<section id="moments" class="scene-story"><div class="scene-intro wrap"><div><p class="eyebrow">${tr('حُبّ يعيش مع يومك','HUBB, WHERE LIFE HAPPENS')}</p><h2>${tr('كل لمّة، لها حُبّ.','Different days.<br>The same little HUBB.')}</h2></div><div class="scene-intro-aside"><p>${tr('من استراحة الملعب، لآخر سالفة على الطاولة. مرّر الصفحة، وشف حُبّ في لحظات مختلفة.','From the edge of the pitch to the last story at the table. Scroll through a few different ways to share HUBB.')}</p><span class="scene-scroll-cue">${tr('كمّل نزول، تتغيّر اللحظة','KEEP SCROLLING. FIND YOUR MOMENT.')} ↓</span></div></div>
<nav class="scene-nav wrap" aria-label="${tr('اختر لحظتك','Choose your moment')}">${scenes.map((s,i)=>`<a href="#moment-${s.id}" data-scene-link="${s.id}" ${i===0?'aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${at(s,'place')}</a>`).join('')}</nav>
<div class="scene-body wrap"><div class="scene-stage"><div class="scene-stage-inner">${scenes.map((s,i)=>`<img class="scene-stage-image ${i===0?'is-active':''}" data-scene-image="${s.id}" src="${s.image}" width="1024" height="1536" loading="lazy" alt="${at(s,'alt')}" ${i!==0?'aria-hidden="true"':''}>`).join('')}<div class="scene-stage-top"><span>HUBB / ${tr('لحظات نتخيّلها','MOMENTS WE IMAGINE')}</span><span class="scene-stage-number" aria-hidden="true">01 / 04</span></div><div class="scene-stage-bottom"><span class="scene-location">${at(scenes[0],'place')}</span><span class="scene-concept">${tr('تصوّر إبداعي مولّد بالذكاء الاصطناعي','AI-GENERATED CREATIVE CONCEPT')}</span></div><div class="scene-stage-progress" aria-hidden="true"><i></i></div></div></div>
<div class="scene-chapters">${scenes.map((s,i)=>`<article class="scene-chapter ${i===0?'is-active':''}" id="moment-${s.id}" data-scene="${s.id}"><figure class="scene-mobile-image"><img src="${s.image}" width="1024" height="1536" loading="lazy" alt="${at(s,'alt')}"><figcaption>${tr('مشهد تصوّري · مولّد بالذكاء الاصطناعي','CREATIVE CONCEPT · AI GENERATED')}</figcaption></figure><div class="scene-chapter-copy"><p class="scene-kicker"><span>${String(i+1).padStart(2,'0')}</span> / ${at(s,'place')}</p><h3>${at(s,'title')}</h3><p class="scene-description">${at(s,'body')}</p><span class="scene-pack-detail">${at(s,'detail')}</span><button class="scene-shop" data-product="${s.product}" data-product-format="${s.format}">${at(s,'cta')} <span aria-hidden="true">↗</span></button></div></article>`).join('')}</div></div>
<div class="scene-outro wrap"><p>${tr('قصص نتخيّلها لحُبّ. وننتظر قصتك أنت.','These are moments we imagine for HUBB. We’d love to hear yours.')}</p><button class="text-link" data-partner="collaboration">${tr('شاركنا فكرتك','Bring us your idea')} ↗</button></div></section>`;
}
