import {t,getLang} from './catalog.js';
const places={factory:{lat:25.131754,lng:46.0797011,title:{ar:'مصنع روزانا الرياض للمواد الغذائية — حريملاء',en:'Rozana Al Riyadh Foodstuff Factory — Huraymila'},url:'https://www.google.com/maps/place/Rozana+Al+Riyadh+Foodstuff+Factory/@25.131754,46.0771262,17z/data=!3m1!4b1!4m6!3m5!1s0x3e2957ded4967ebb:0x9820725213d7f568!8m2!3d25.131754!4d46.0797011!16s%2Fg%2F11vpt7ngn7'},warehouse:{lat:24.5634184,lng:46.7556442,title:{ar:'روزانا للمواد الغذائية — مستودع الرياض',en:'Rozana Foodstuff — Riyadh warehouse'},url:'https://www.google.com/maps/place/Rozana+foodstuff/@24.5631677,46.7553478,19.8z/data=!4m6!3m5!1s0x3e2f093c04bcac1d:0x5bb58ad0c4dcee22!8m2!3d24.5634184!4d46.7556442!16s%2Fg%2F11n72754c1'}};
export function initStory(){
let step=0,place='factory',context;
const art=document.querySelector('.crack-art');
const steps=()=>[
{title:t('حبّة واحدة. على مهلك.','One seed. Take your time.'),body:t('خذ حبّة واحدة من الكيس. القشر الخارجي يحمي النواة؛ النواة داخلها هي الجزء اللي نأكله.','Take one seed from the sachet. The outer husk holds the kernel. That smaller kernel inside is the part we eat.'),note:t('الصورة توضّح القشر والنواة منفصلين.','The image shows the husk and kernel separately.')},
{title:t('كسر خفيف، على الحافة.','A gentle crack along the edge.'),body:t('امسك حبّة واحدة عند طرف الأسنان الأمامية واضغط بخفّة ليفتح القشر. بعدها أبعدها وافصل القشر بأصابعك.','Hold one seed at the edge of your front teeth and gently crack the husk. Then remove it and separate the shell with your fingers.'),note:t('لا تمضغ الحبّة كاملة، ولا تستخدم قوة إذا ما انفتح القشر.','Do not chew the whole seed or force a husk that will not open.')},
{title:t('النواة هي المكافأة.','The kernel is what you came for.'),body:t('افصل نصفي القشر، وأخرج النواة. كُل النواة فقط، وانتبه لقرمشتها والتحميص والنكهة.','Separate the two husk halves and take out the kernel. Eat only the kernel. Notice its crunch, roast and flavour.'),note:t('القشر لا يؤكل. تخلّص من أي أجزاء قشر قبل الأكل.','The husk is not food. Remove any shell fragments before eating.')},
{title:t('خلّ القشور في كيسها.','A little care for the gathering.'),body:t('اجمع القشور في الكيس المنفصل المخصص لها. لا ترجعها إلى كيس الطعام أو الكوب. كذا تبقى اللمّة مرتّبة.','Collect discarded husks in the separate shell bag. Keep them out of the food sachet and cup. A small habit that keeps the gathering tidy.'),note:t('جرّب النكهة، وبعدها شاركنا رأيك الصادق.','Try the flavour. Then tell us what you really think.')}
];
function renderStep(){const item=steps()[step];art.dataset.step=String(step);document.querySelectorAll('[data-crack-step]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.crackStep)===step)));document.querySelector('#crack-step-copy').innerHTML=`<h3>${item.title}</h3><p>${item.body}</p><small>${item.note}</small>`;}
function renderPlace(change=true){const p=places[place];document.querySelectorAll('[data-location]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.location===place)));const map=document.querySelector('#location-map');map.title=p.title[getLang()];if(change)map.src=`https://maps.google.com/maps?q=${p.lat},${p.lng}&z=15&output=embed&hl=${getLang()}`;document.querySelector('#location-directions').href=p.url;}
document.querySelectorAll('[data-crack-step]').forEach(b=>b.onclick=()=>{step=Number(b.dataset.crackStep);renderStep();});document.querySelector('#crack-next').onclick=()=>{step=(step+1)%4;renderStep();};document.querySelectorAll('[data-location]').forEach(b=>b.onclick=()=>{place=b.dataset.location;renderPlace();});
const sound=document.querySelector('#crack-sound');sound.onclick=async()=>{if(sound.getAttribute('aria-pressed')==='true')return;try{const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw new Error('unsupported');context??=new Audio();await context.resume();const now=context.currentTime;for(const [delay,duration,level,freq] of [[0,.06,.09,2100],[.035,.105,.055,4200],[.10,.035,.025,1300]]){const buffer=context.createBuffer(1,Math.ceil(context.sampleRate*duration),context.sampleRate);const data=buffer.getChannelData(0);for(let i=0;i<data.length;i++)data[i]=(Math.random()*2-1)*Math.pow(1-i/data.length,3);const source=context.createBufferSource();source.buffer=buffer;const filter=context.createBiquadFilter();filter.type='highpass';filter.frequency.value=freq;const gain=context.createGain();gain.gain.value=level;source.connect(filter).connect(gain).connect(context.destination);source.start(now+delay);source.onended=()=>{source.disconnect();filter.disconnect();gain.disconnect();};}sound.setAttribute('aria-pressed','true');step=1;renderStep();setTimeout(()=>sound.setAttribute('aria-pressed','false'),500);}catch{sound.textContent=t('الصوت غير متاح في هذا المتصفح.','Sound is unavailable in this browser.');}};
window.addEventListener('hubb:language',()=>{renderStep();renderPlace(false);});renderStep();renderPlace();
}
